PL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL/Controllers/MedicamentoController.cs
using ML;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class MedicamentoController : Controller
    {
        // GET: Medicamento
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Result result = BL.Medicamento.GetAll();

            return View(result);
        }

        [HttpGet]
        public ActionResult Form(int? idMedicamento)
        {
            ML.Medicamento medicamento = new ML.Medicamento();
            ML.Result resultProveedores = BL.Proveedor.GetAll();

            if (idMedicamento != null)
            {
                //GetById
                ML.Result result = BL.Medicamento.GetById(idMedicamento.Value);

                if (result.Status)
                {
                    medicamento = (ML.Medicamento)result.Object;
                }
            }
            else
            {
                medicamento.Proveedor = new ML.Proveedor();
            }

            medicamento.Proveedor.Proveedores = resultProveedores.Objects;

            return View(medicamento);
        }

        [HttpPost]
        public ActionResult Formulario(ML.Medicamento medicamento)
        {
            if (medicamento.IdMedicamento == 0)
            {
                //Add

                ML.Result result = BL.Medicamento.Add(medicamento);
                if (result.Status)
                {
                    ViewBag.Success = true;
                    ViewBag.Message = "Medicamento agregado con éxito.";
                }
                else
                {
                    ViewBag.Success = false;
                    ViewBag.Message = $"Error: {result.Message}";
                }
            }
            else
            {
                //Update
                ML.Result result = BL.Medicamento.Update(medicamento);
                if (result.Status)
                {
                    ViewBag.Success = true;
                    ViewBag.Message = "Medicamento modificado con éxito.";
                }
                else
                {
                    ViewBag.Success = false;
                    ViewBag.Message = $"Error: {result.Message}";
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult Delete(int? idMedicamento)
        {
            if (idMedicamento == null)
            {
                ViewBag.Success = false;
                ViewBag.Message = "Error: No se encontró el ID.";
            }
            else
            {
                ML.Result result = BL.Medicamento.Delete(idMedicamento.Value);

                if (result.Status)
                {
                    ViewBag.Success = true;
                    ViewBag.Message = "Medicamento eliminado con éxito.";
                }
                else
                {
                    ViewBag.Success = false;
                    ViewBag.Message = $"Error: {result.Message}";
                }
            }

            return View("Formulario");
        }
    }
}

PL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PL/Views/Medicamento/Form.cshtml
@model ML.Medicamento
@{
    ViewBag.Title = "Form";
}

<h2>Formulario de medicamento</h2>

<div class="container">
    @using (Html.BeginForm("Formulario", "Medicamento", FormMethod.Post, new {enctype = "multipart/form-data"} ))
    {
        <div class="row">
            <div class="col-md-12">
                <div style="display:none">
                    @Html.TextBoxFor(Model => Model.IdMedicamento, new { @class = "form-control" })
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-3">
                            @Html.Label("Nombre:")
                            @Html.TextBoxFor(Model => Model.Nombre, new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-3">
                            @Html.Label("Descripción:")
                            @Html.TextBoxFor(Model => Model.Descripcion, new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-3">
                            @Html.Label("Fecha de caducidad:")
                            @Html.TextBoxFor(Model => Model.FechaCaducidad, new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-3">
                            @Html.Label("Precio unitario:")
                            @Html.TextBoxFor(Model => Model.PrecioUnitario, new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-3">
                            @Html.Label("Stock:")
                            @Html.TextBoxFor(Model => Model.Stock, new { @class = "form-control" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-md-3">
                            @Html.Label("Proveedor:")
                            @Html.DropDownListFor(Model => Model.Proveedor.IdProveedor, new SelectList(Model.Proveedor.Proveedores, "IdProveedor", "Nombre"), "- Selecciona un proveedor", new {@class="form-control"})
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <input type="submit" class="btn btn-success" value="Guardar" />
                @Html.ActionLink("Regresar", "GetAll", "Medicamento", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    }
</div>

PL/Views/Medicamento/Formulario.cshtml
@{
    ViewBag.Title = "Formulario";
}

<h2>Respuesta</h2>

@if (ViewBag.Success)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}
else
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.Message
    </div>
}

@Html.ActionLink("Regresar", "GetAll", "Medicamento", htmlAttributes: new { @class = "btn btn-danger" })

PL/Views/Medicamento/GetAll.cshtml
@model ML.Result
@{
    ViewBag.Title = "GetAll";
}

<h2>Medicamentos</h2>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h4>Selecciona el botón verde "+" para añadir nuevos elementos.</h4>
        </div>
        <div class="col-md-6">
            @Html.ActionLink("+", "Form", "Medicamento", htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>
</div>

<div class="container">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Editar</th>
                <th>ID</th>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Fecha de caducidad</th>
                <th>Precio unitario</th>
                <th>Stock</th>
                <th>Proveedor</th>
                <th>Eliminar</th>
            </tr>
        </thead>

        <tbody>
            @foreach (ML.Medicamento medicamento in Model.Objects)
            {
                <tr>
                    <td><a class="btn btn-warning" href="@Url.Action("Form", "Medicamento", new { idMedicamento = medicamento.IdMedicamento })">Editar</a></td>
                    <td>@medicamento.IdMedicamento</td>
                    <td>@medicamento.Nombre</td>
                    <td>@medicamento.Descripcion</td>
                    <td>@medicamento.FechaCaducidad</td>
                    <td>$@medicamento.PrecioUnitario C/U</td>
                    <td>@medicamento.Stock</td>
                    <td>@medicamento.Proveedor.Nombre</td>
                    <td><a class="btn btn-danger" href="@Url.Action("Delete", "Medicamento", new { idMedicamento = medicamento.IdMedicamento })" onclick = "return confirm('¿Estás seguro que deseas eliminar el medicamento?');">Eliminar</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Medicamentos", "GetAll", "Medicamento")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>